#!/usr/bin/env python3

#This should only be run from a system with postfix installed

import argparse
import smtplib
from email.mime.text import MIMEText

SMTPSERVER = 'localhost'

def get_args():
    parser = argparse.ArgumentParser(description='Simple Mail Tool')
    parser.add_argument('--to', '-t', required=True, help='To recipient')
    parser.add_argument('--subject', '-s', required=True, help='Subject')
    parser.add_argument('messagefile',
                        help='File containing the message to send')
    return parser.parse_args()

def main():
    args = get_args()
    with open(args.messagefile) as mailfile:
        msg = MIMEText(mailfile.read())

    msg['Subject'] = args.subject
    msg['From'] = 'noreply@canonical.com'
    msg['To'] = args.to

    s = smtplib.SMTP(SMTPSERVER)
    s.send_message(msg)
    s.quit()

if __name__ == '__main__':
    main()
