#!/usr/bin/env bash
#
# Copyright 2023 Canonical Ltd.
#
# this exports SSH_OPTS to the environment (and subsequent scripts)
# it contains options to make ssh more friendly to automation
# it also sets the default user to ubuntu if it wasn't supplied 
# in the environment

generate_ssh_opts() {
    
  SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -l ${DEVICE_USER:-ubuntu}"
  echo "$SSH_OPTS"
}

export SSH_OPTS=$(generate_ssh_opts)
