#!/usr/bin/env bash

# Copyright 2023 Canonical Ltd.
# Written by:
#   Maciej Kisielewski <maciej.kisielewski@canonical.com>
#
# This script waits for all snap operations on a remote device to complete.
# It uses SSH to query the snap changes on the device and checks for any ongoing operations.
# The script will retry up to 40 times, with a 30-second sleep between each attempt.
# This script is intended to be a drop-in replacement for inline convenience
# functions previously defined in each of the Jenkins jobs.
#
# Dependencies:
#     This script depends on SSH and assumes that SSH options and DEVICE_IP are set.
#
# Usage:
#     Run directly:
#     `wait_for_snap_complete <command> [command_args ...]`
#     Or source it in another script and call
#     `wait_for_snap_complete_function`

wait_for_snap_complete_function() {
    source "$(dirname "$BASH_SOURCE")/set-ssh-options"
    set +x
    loopcnt=0
    until [ $loopcnt -gt 40 ]
    do
        loopcnt=$((loopcnt+1))
        changes="$(ssh $SSH_OPTS $DEVICE_IP 'sudo snap changes')"
        echo Checking for all snap operations to complete...
        echo $changes
        if [ -n "$changes" ] &&
            [[ "$changes" != *"Doing"* ]] &&
            [ "$(ssh $SSH_OPTS $DEVICE_IP echo true)" = "true" ]; then
            done="true"
            break
        else
            sleep 30
        fi
    done
    if [ -z "$done" ]; then
        echo "ERROR: Timeout waiting for snap operations!"
        return 1
    fi
    set -x
    return 0
}

# Check if the script is being sourced or executed
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  wait_for_snap_complete_function "$@"
fi